package com.mkyong.stock;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockTransaction generated by hbm2java
 */
@Entity
@Table(name = "stock_transaction", catalog = "mkyong")
@org.hibernate.annotations.Entity(
		dynamicInsert = true,
		dynamicUpdate = true
)
public class StockTransaction implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer stockId;
	private Date date;
	private Integer priceChange;
	private Integer priceClose;
	private Integer priceOpen;
	private Integer volume;

	public StockTransaction() {
	}

	public StockTransaction(Date date, Integer priceChange, Integer priceClose, Integer priceOpen, Integer volume) {
		this.date = date;
		this.priceChange = priceChange;
		this.priceClose = priceClose;
		this.priceOpen = priceOpen;
		this.volume = volume;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STOCK_ID", unique = true, nullable = false)
	public Integer getStockId() {
		return this.stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "PRICE_CHANGE")
	public Integer getPriceChange() {
		return this.priceChange;
	}

	public void setPriceChange(Integer priceChange) {
		this.priceChange = priceChange;
	}

	@Column(name = "PRICE_CLOSE")
	public Integer getPriceClose() {
		return this.priceClose;
	}

	public void setPriceClose(Integer priceClose) {
		this.priceClose = priceClose;
	}

	@Column(name = "PRICE_OPEN")
	public Integer getPriceOpen() {
		return this.priceOpen;
	}

	public void setPriceOpen(Integer priceOpen) {
		this.priceOpen = priceOpen;
	}

	@Column(name = "VOLUME")
	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

}
